### ISSUE TITLE
RPI 3+ Debian 10.4 make fails with error: implicit declaration of function ‘pci_request_region’

### ISSUE THREAD

**Issue by quarterturn** [patjak/bcwc_pcie#216]
prereqs installed via `apt-get install linux-headers git kmod libssl-dev checkinstall`
kernel source installed via `git clone https://github.com/notro/rpi-source.git`
firmware extracted

Tried both master and main brances, same result for 'make':

`make -C /lib/modules/4.19.83-v7+/build M=/tmp/bcwc_pcie modules
make[1]: Entering directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
  CC [M]  /tmp/bcwc_pcie/fthd_ddr.o
  CC [M]  /tmp/bcwc_pcie/fthd_hw.o
  CC [M]  /tmp/bcwc_pcie/fthd_drv.o
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_reserve_mem’:
/tmp/bcwc_pcie/fthd_drv.c:50:8: error: implicit declaration of function ‘pci_request_region’; did you mean pci_request_regions’? [-Werror=implicit-function-declaration]
  ret = pci_request_region(dev_priv->pdev, FTHD_PCI_S2_IO, "S2 IO");
        ^~~~~~~~~~~~~~~~~~
        pci_request_regions
/tmp/bcwc_pcie/fthd_drv.c:59:3: error: implicit declaration of function ‘pci_release_region’; did you mean pci_release_regions’? [-Werror=implicit-function-declaration]
   pci_release_region(dev_priv->pdev, FTHD_PCI_S2_IO);
   ^~~~~~~~~~~~~~~~~~
   pci_release_regions
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_remove’:
/tmp/bcwc_pcie/fthd_drv.c:355:2: error: implicit declaration of function ‘pci_disable_msi’; did you mean ‘pci_disable_sriov’? [-Werror=implicit-function-declaration]
  pci_disable_msi(pdev);
  ^~~~~~~~~~~~~~~
  pci_disable_sriov
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_init’:
/tmp/bcwc_pcie/fthd_drv.c:391:8: error: implicit declaration of function ‘pci_enable_msi’; did you mean ‘pci_enable_sriov’? [-Werror=implicit-function-declaration]
  ret = pci_enable_msi(pdev);
        ^~~~~~~~~~~~~~
        pci_enable_sriov
/tmp/bcwc_pcie/fthd_drv.c: At top level:
/tmp/bcwc_pcie/fthd_drv.c:558:1: warning: data definition has no type or storage class
 module_pci_driver(fthd_pci_driver);
 ^~~~~~~~~~~~~~~~~
/tmp/bcwc_pcie/fthd_drv.c:558:1: error: type defaults to ‘int’ in declaration of ‘module_pci_driver’ [-Werror=implicit-int]
/tmp/bcwc_pcie/fthd_drv.c:558:1: warning: parameter names (without types) in function declaration
/tmp/bcwc_pcie/fthd_drv.c:547:26: warning: ‘fthd_pci_driver’ defined but not used [-Wunused-variable]
 static struct pci_driver fthd_pci_driver = {
                          ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:304: /tmp/bcwc_pcie/fthd_drv.o] Error 1
make[1]: *** [Makefile:1525: _module_/tmp/bcwc_pcie] Error 2
make[1]: Leaving directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
make: *** [Makefile:12: all] Error 2
root@matrixpi:/tmp/bcwc_pcie# make clean
make -C /lib/modules/4.19.83-v7+/build M=/tmp/bcwc_pcie clean
make[1]: Entering directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
  CLEAN   /tmp/bcwc_pcie/.tmp_versions
make[1]: Leaving directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
root@matrixpi:/tmp/bcwc_pcie# make
make -C /lib/modules/4.19.83-v7+/build M=/tmp/bcwc_pcie modules
make[1]: Entering directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
  CC [M]  /tmp/bcwc_pcie/fthd_ddr.o
  CC [M]  /tmp/bcwc_pcie/fthd_hw.o
  CC [M]  /tmp/bcwc_pcie/fthd_drv.o
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_reserve_mem’:
/tmp/bcwc_pcie/fthd_drv.c:50:8: error: implicit declaration of function ‘pci_request_region’; did you mean pci_request_regions’? [-Werror=implicit-function-declaration]
  ret = pci_request_region(dev_priv->pdev, FTHD_PCI_S2_IO, "S2 IO");
        ^~~~~~~~~~~~~~~~~~
        pci_request_regions
/tmp/bcwc_pcie/fthd_drv.c:59:3: error: implicit declaration of function ‘pci_release_region’; did you mean pci_release_regions’? [-Werror=implicit-function-declaration]
   pci_release_region(dev_priv->pdev, FTHD_PCI_S2_IO);
   ^~~~~~~~~~~~~~~~~~
   pci_release_regions
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_remove’:
/tmp/bcwc_pcie/fthd_drv.c:355:2: error: implicit declaration of function ‘pci_disable_msi’; did you mean ‘pci_disable_sriov’? [-Werror=implicit-function-declaration]
  pci_disable_msi(pdev);
  ^~~~~~~~~~~~~~~
  pci_disable_sriov
/tmp/bcwc_pcie/fthd_drv.c: In function ‘fthd_pci_init’:
/tmp/bcwc_pcie/fthd_drv.c:391:8: error: implicit declaration of function ‘pci_enable_msi’; did you mean ‘pci_enable_sriov’? [-Werror=implicit-function-declaration]
  ret = pci_enable_msi(pdev);
        ^~~~~~~~~~~~~~
        pci_enable_sriov
/tmp/bcwc_pcie/fthd_drv.c: At top level:
/tmp/bcwc_pcie/fthd_drv.c:558:1: warning: data definition has no type or storage class
 module_pci_driver(fthd_pci_driver);
 ^~~~~~~~~~~~~~~~~
/tmp/bcwc_pcie/fthd_drv.c:558:1: error: type defaults to ‘int’ in declaration of ‘module_pci_driver’ [-Werror=implicit-int]
/tmp/bcwc_pcie/fthd_drv.c:558:1: warning: parameter names (without types) in function declaration
/tmp/bcwc_pcie/fthd_drv.c:547:26: warning: ‘fthd_pci_driver’ defined but not used [-Wunused-variable]
 static struct pci_driver fthd_pci_driver = {
                          ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:304: /tmp/bcwc_pcie/fthd_drv.o] Error 1
make[1]: *** [Makefile:1525: _module_/tmp/bcwc_pcie] Error 2
make[1]: Leaving directory '/root/linux-3c235dcfe80a7c7ba360219e4a3ecb256f294376'
make: *** [Makefile:12: all] Error 2`

**Comment by quarterturn** [comment]
I should note this is a Facetime HD camera liberated from a mid-2011 27' iMac and wired up with a regular USB jack. It works fine on Ubuntu 18.04 x86-x64.

**Comment by quarterturn** [comment]
Whoops usb not pcie sorry didn't notice that before!
