### ISSUE TITLE
I cannot compile on Ubuntu 14.04 kernel 3.16.0-60-generic

### ISSUE THREAD

**Issue by kristB** [patjak/bcwc_pcie#71]
When I try to compile I get following error

==============================================
root@XIIApostoli:/krist/Downloads/bcwc_pcie# sudo make
make -C /lib/modules/3.16.0-60-generic/build M=/krist/Downloads/bcwc_pcie modules
make[1]: Map '/usr/src/linux-headers-3.16.0-60-generic' wordt binnengegaan
  CC [M]  /krist/Downloads/bcwc_pcie/fthd_v4l2.o
/krist/Downloads/bcwc_pcie/fthd_v4l2.c: In function ‘fthd_v4l2_register’:
/krist/Downloads/bcwc_pcie/fthd_v4l2.c:705:2: error: implicit declaration of function ‘vb2_dma_sg_init_ctx’ [-Werror=implicit-function-declaration]
  dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
  ^
/krist/Downloads/bcwc_pcie/fthd_v4l2.c:705:22: warning: assignment makes pointer from integer without a cast [enabled by default]
  dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
                      ^
/krist/Downloads/bcwc_pcie/fthd_v4l2.c: In function ‘fthd_v4l2_unregister’:
/krist/Downloads/bcwc_pcie/fthd_v4l2.c:740:2: error: implicit declaration of function ‘vb2_dma_sg_cleanup_ctx’ [-Werror=implicit-function-declaration]
  vb2_dma_sg_cleanup_ctx(dev_priv->alloc_ctx);
  ^
cc1: some warnings being treated as errors
make[2]: *** [/krist/Downloads/bcwc_pcie/fthd_v4l2.o] Fout 1
make[1]: *** [_module_/krist/Downloads/bcwc_pcie] Fout 2
make[1]: Map '/usr/src/linux-headers-3.16.0-60-generic' wordt verlaten
make: *** [all] Fout 2
root@XIIApostoli:/krist/Downloads/bcwc_pcie#

====================================================================

does anyone have an idea ??

many many tnx for the effort already done on developing this 

greetings 
Krist

**Comment by patjak** [comment]
Hi Krist

Your kernel is too old, please see the wiki.
