### ISSUE TITLE
Installing the driver fails on Linux 7.2.2

### ISSUE THREAD

**Issue by SameerAhmed419** [patjak/bcwc_pcie#339]
Have a look:
**`sudo dkms autoinstall`** 
```
Sign command: /usr/lib/modules/7.2.2-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Autoinstall of module facetimehd/0.7.0.1.r0.g805d865 for kernel 7.2.2-arch1-1 (x86_64)
Building module(s)....(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=7.2.2-arch1-1 -C /usr/lib/modules/7.2.2-arch1-1/build M=/var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build

Error! Bad return status for module build on kernel: 7.2.2-arch1-1 (x86_64)
Consult /var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build/make.log for more information.

Autoinstall on 7.2.2-arch1-1 succeeded for module(s) broadcom-wl.
Autoinstall on 7.2.2-arch1-1 failed for module(s) facetimehd(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
```
**`sudo tail -60 /var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build/make.log`**
```
DKMS (dkms-3.4.3) make.log for facetimehd/0.7.0.1.r0.g805d865 for kernel 7.2.2-arch1-1 (x86_64)
Thu Sep  3 03:27:31 PM CEST 2026

Building module(s)
# command: make -j4 KERNELRELEASE=7.2.2-arch1-1 -C /usr/lib/modules/7.2.2-arch1-1/build M=/var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build
make: Entering directory '/usr/lib/modules/7.2.2-arch1-1/build'
make[1]: Entering directory '/var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build'
  CC [M]  fthd_ddr.o
  CC [M]  fthd_hw.o
  CC [M]  fthd_drv.o
  CC [M]  fthd_ringbuf.o
  CC [M]  fthd_isp.o
  CC [M]  fthd_v4l2.o
  CC [M]  fthd_buffer.o
  CC [M]  fthd_debugfs.o
fthd_v4l2.c: In function ‘fthd_v4l2_ioctl_enum_fmt_vid_cap’:
fthd_v4l2.c:391:9: error: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
  391 |         strncpy(fmt->description, desc, sizeof(fmt->description));
      |         ^~~~~~~
fthd_v4l2.c:25:1: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
   24 | #include "fthd_isp.h"
  +++ |+#include <string.h>
   25 | #include "fthd_ringbuf.h"
fthd_v4l2.c:391:9: warning: incompatible implicit declaration of built-in function ‘strncpy’ [-Wbuiltin-declaration-mismatch]
  391 |         strncpy(fmt->description, desc, sizeof(fmt->description));
      |         ^~~~~~~
fthd_v4l2.c:391:9: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
make[3]: *** [/usr/lib/modules/7.2.2-arch1-1/build/scripts/Makefile.build:289: fthd_v4l2.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/7.2.2-arch1-1/build/Makefile:2187: .] Error 2
make[1]: *** [/usr/lib/modules/7.2.2-arch1-1/build/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/facetimehd/0.7.0.1.r0.g805d865/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/7.2.2-arch1-1/build'

# exit code: 2
# elapsed time: 00:00:06
```
**Environment Details (`sudo inxi -Fxz`)**
```
System:
  Kernel: 7.2.2-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 16.2.1
  Desktop: Sway v: 1.12 Distro: Arch Linux
Machine:
  Type: Laptop System: Apple product: MacBookAir6,2 v: 1.0 serial: <filter>
  Mobo: Apple model: Mac-7DF21CB3ED6977E5 v: MacBookAir6,2
    serial: <filter> Firmware: UEFI vendor: Apple
    v: MBA61.88Z.0107.B00.1804111137 date: 04/11/2018
Battery:
  ID-1: BAT0 charge: 38.5 Wh (95.2%) condition: 40.4/54.3 Wh (74.4%)
    temp: 38.2 C volts: 8.53 min: 7.6 model: DP bq20z451 status: charging
CPU:
  Info: dual core model: Intel Core i5-4250U bits: 64 type: MT MCP
    arch: Haswell rev: 1 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 2300 min/max: 800/2600 cores: 1: 2300 2: 2300 3: 2300
    4: 2300 bogomips: 15198
  Flags-basic: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3
    vmx
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Apple
    driver: i915 v: kernel arch: Gen-7.5 bus-ID: 00:02.0
  Display: unspecified server: Xwayland v: 24.1.13 driver: X:
    loaded: modesetting dri: crocus gpu: i915 resolution: 1440x900
  API: EGL v: 1.5 drivers: crocus,swrast platforms:
    active: gbm,surfaceless,device inactive: wayland,x11
  API: OpenGL v: 4.6 vendor: mesa v: 26.2.2-arch1.1 note: incomplete
    (EGL sourced) renderer: Mesa Intel HD Graphics 5000 (HSW GT3),
    llvmpipe (LLVM 22.1.8 256 bits)
  API: Vulkan v: 1.4.357 drivers: intel surfaces: N/A devices: 1
  Info: Tools: api: eglinfo, glxinfo, vulkaninfo gpu: gputop,
    intel_gpu_top, lsgpu wl: swaymsg x11: xprop,xrandr
Audio:
  Device-1: Intel Haswell-ULT HD Audio vendor: Apple driver: snd_hda_intel
    v: kernel bus-ID: 00:03.0
  Device-2: Intel 8 Series HD Audio driver: snd_hda_intel v: kernel
    bus-ID: 00:1b.0
  Device-3: Broadcom 720p FaceTime HD Camera driver: N/A bus-ID: 02:00.0
  API: ALSA v: k7.2.2-arch1-1 status: kernel-api
  Server-1: sndiod v: N/A status: off
  Server-2: PipeWire v: 1.6.8 status: n/a (root, process)
Network:
  Device-1: Broadcom BCM4360 802.11ac Dual Band Wireless Network Adapter
    vendor: Apple driver: wl v: kernel bus-ID: 03:00.0
  IF: wlan0 state: up mac: <filter>
Bluetooth:
  Device-1: Apple Bluetooth USB Host Controller driver: btusb v: 0.8
    type: USB bus-ID: 1-3.3:6
  Report: btmgmt ID: hci0 rfk-id: 1 state: down bt-service: disabled
    rfk-block: hardware: no software: no address: N/A
Drives:
  Local Storage: total: 233.76 GiB used: 158.08 GiB (67.6%)
  ID-1: /dev/sda vendor: Apple model: SSD SM0256F size: 233.76 GiB
Partition:
  ID-1: / size: 233.26 GiB used: 157.82 GiB (67.7%) fs: f2fs dev: /dev/sda2
  ID-2: /boot size: 511 MiB used: 264.7 MiB (51.8%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: zram size: 7.51 GiB used: 158 MiB (2.1%)
    dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 72.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 4 GiB available: 3.76 GiB used: 2.29 GiB (61.1%)
    igpu: 32 MiB
  Processes: 177 Uptime: 17m Init: systemd
  Packages: 1361 Compilers: clang: 22.1.8 gcc: 16.2.1 Shell: Sudo
    v: 1.9.17p2 inxi: 3.3.41

```

**Comment by SameerAhmed419** [comment]
The issue got fixed by an update.
