### ISSUE TITLE
Can't build on F29 4.19.2-300

### ISSUE THREAD

**Issue by dac73** [patjak/bcwc_pcie#168]
make
make -C /lib/modules/4.19.2-300.fc29.x86_64/build M=/home/dario/Projects/github/bcwc_pcie modules
make[1]: Entering directory '/usr/src/kernels/4.19.2-300.fc29.x86_64'
  CC [M]  /home/dario/Projects/github/bcwc_pcie/fthd_ddr.o
In file included from /home/dario/Projects/github/bcwc_pcie/fthd_ddr.c:21:
/home/dario/Projects/github/bcwc_pcie/fthd_drv.h:121:5: warning: "LINUX_VERSION_CODE" is not defined, evaluates to 0 [-Wundef]
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,8,0)
     ^~~~~~~~~~~~~~~~~~
/home/dario/Projects/github/bcwc_pcie/fthd_drv.h:121:26: warning: "KERNEL_VERSION" is not defined, evaluates to 0 [-Wundef]
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,8,0)
                          ^~~~~~~~~~~~~~
/home/dario/Projects/github/bcwc_pcie/fthd_drv.h:121:40: error: missing binary operator before token "("
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,8,0)
                                        ^
make[2]: *** [scripts/Makefile.build:306: /home/dario/Projects/github/bcwc_pcie/fthd_ddr.o] Error 1
make[1]: *** [Makefile:1521: _module_/home/dario/Projects/github/bcwc_pcie] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.19.2-300.fc29.x86_64'
make: *** [Makefile:12: all] Error 2

**Comment by darren-steven** [comment]
linux/version.h needs to be included. It's not explicitly in thepath of other includes (or something) in 4.19 by the looks. I can build if I #include linux/version.h in all the .c files, but then hit #165

**Comment by frgt10** [comment]
> linux/version.h needs to be included. It's not explicitly in thepath of other includes (or something) in 4.19 by the looks. I can build if I #include linux/version.h in all the .c files, but then hit #165

+1

**Comment by nhed** [comment]
Worked for me on 4.19.4-300.fc29.x86_64 using the `mainline` instead of `master`

**Comment by dlondero** [comment]
Same here on 4.19.2-301.fc29.x86_64 using `mainline`. google-meet works, chees not.

**Comment by antmachine** [comment]
+1

**Comment by vejeta** [comment]
Confirmed that it compiles with the `mainline` github branch.

**Comment by patjak** [comment]
Should be fixed now in the master branch.
