### ISSUE TITLE
Fails to build on Linux 4.8

### ISSUE THREAD

**Issue by ronin13** [patjak/bcwc_pcie#103]
```
 DKMS make.log for bcwc-pcie-0r229.48f9854 for kernel 4.8.1-1-ARCH (x86_64)
 Sun Oct 16 17:38:16 BST 2016
 make: Entering directory '/usr/lib/modules/4.8.1-1-ARCH/build'
   LD      /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/built-in.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_ddr.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_hw.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_drv.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_ringbuf.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_isp.o
   CC [M]  /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.o
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c:298:28: error: initialization from incompatible pointer type [-Werror=incom patible-pointer-types]
   .queue_setup            = fthd_buffer_queue_setup,
                             ^~~~~~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c:298:28: note: (near initialization for ‘vb2_queue_ops.queue_setup’)
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c: In function ‘fthd_v4l2_register’:
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c:714:24: error: implicit declaration of function ‘vb2_dma_sg_init_ctx’ [-Wer ror=implicit-function-declaration]
   dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
                         ^~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c:714:22: warning: assignment makes pointer from integer without a cast [-Win t-conversion]
   dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
                       ^
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c: In function ‘fthd_v4l2_unregister’:
 /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.c:749:2: error: implicit declaration of function ‘vb2_dma_sg_cleanup_ctx’ [-W error=implicit-function-declaration]
   vb2_dma_sg_cleanup_ctx(dev_priv->alloc_ctx);
   ^~~~~~~~~~~~~~~~~~~~~~
 cc1: some warnings being treated as errors
 make[1]: *** [scripts/Makefile.build:290: /var/lib/dkms/bcwc-pcie/0r229.48f9854/build/fthd_v4l2.o] Error 1
 make: *** [Makefile:1471: _module_/var/lib/dkms/bcwc-pcie/0r229.48f9854/build] Error 2
 make: Leaving directory '/usr/lib/modules/4.8.1-1-ARCH/build'
```

This happens because of this commit https://patchwork.kernel.org/patch/8907111/

```
 commit 36c0f8b32c4bd4f668cedfba6d97afaa84f055fb
 Author: Hans Verkuil <hans.verkuil@cisco.com>
 Date:   Fri Apr 15 09:15:05 2016 -0300
 
     [media] vb2: replace void *alloc_ctxs by struct device *alloc_devs
     
     Make this a proper typed array. Drop the old allocate context code since
     that is no longer used.
     
     Note that the memops functions now get a struct device pointer instead of
     the struct device ** that was there initially (actually a void pointer to
     a struct containing only a struct device pointer).
     
     This code is now a lot cleaner.
     
     Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
     Reviewed-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
     Cc: Sakari Ailus <sakari.ailus@iki.fi>
     Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>
```

**Comment by patjak** [comment]
Already fixed in the mainline branch but I also just merged a fix for the master branch. Thanks for poking me about this. Cheers.
